run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: exported
      - name: error-return
      - name: error-strings
