package archai

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
)

// WriteJSON emits the architecture model as indented JSON. The output
// is byte-stable across runs (helpers in model.go sort everything
// they emit) so snapshot tests can diff verbatim.
func WriteJSON(w io.Writer, m ArchitectureModel) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	return enc.Encode(m)
}

// WriteYAML emits a minimal hand-rolled YAML rendering of the model.
//
// We don't import an external YAML library here. The model is a small,
// well-defined struct with no cycles or polymorphic fields, so the
// hand-rolled emitter is dramatically simpler than pulling in a
// dependency just for the bridge command. If the document grows beyond
// what this emitter can handle, swap in gopkg.in/yaml.v3 with no
// changes to the model schema.
//
// Determinism: same struct, same output. We rely on the map-free shape
// of the document — every field is either a primitive, a struct, or a
// slice — to emit field order in the order they appear in the structs.
func WriteYAML(w io.Writer, m ArchitectureModel) error {
	var b strings.Builder
	b.WriteString("# Generated by archmotif export --format archai-model\n")
	b.WriteString("# Schema: " + SchemaName + " v" + strconv.Itoa(CurrentSchemaVersion) + "\n")
	yamlSchema(&b, m.Schema)
	yamlSource(&b, m.Source)
	yamlFacets(&b, m.Facets)
	yamlStereotypes(&b, m.Stereotypes)
	yamlPackages(&b, m.Packages)
	yamlSymbols(&b, m.Symbols)
	yamlDependencies(&b, m.Dependencies)
	_, err := io.WriteString(w, b.String())
	return err
}

func yamlSchema(b *strings.Builder, s Schema) {
	b.WriteString("schema:\n")
	fmt.Fprintf(b, "  name: %s\n", yamlString(s.Name))
	fmt.Fprintf(b, "  version: %d\n", s.Version)
}

func yamlSource(b *strings.Builder, s Source) {
	b.WriteString("source:\n")
	fmt.Fprintf(b, "  tool: %s\n", yamlString(s.Tool))
	fmt.Fprintf(b, "  format: %s\n", yamlString(s.Format))
	b.WriteString("  counts:\n")
	fmt.Fprintf(b, "    packages: %d\n", s.Counts.Packages)
	fmt.Fprintf(b, "    symbols: %d\n", s.Counts.Symbols)
	fmt.Fprintf(b, "    dependencies: %d\n", s.Counts.Dependencies)
}

func yamlFacets(b *strings.Builder, fs []Facet) {
	if len(fs) == 0 {
		b.WriteString("facets: []\n")
		return
	}
	b.WriteString("facets:\n")
	for _, f := range fs {
		fmt.Fprintf(b, "  - id: %s\n", yamlString(f.ID))
		if f.Description != "" {
			fmt.Fprintf(b, "    description: %s\n", yamlString(f.Description))
		}
	}
}

func yamlStereotypes(b *strings.Builder, ss []Stereotype) {
	if len(ss) == 0 {
		b.WriteString("stereotypes: []\n")
		return
	}
	b.WriteString("stereotypes:\n")
	for _, s := range ss {
		fmt.Fprintf(b, "  - id: %s\n", yamlString(s.ID))
		fmt.Fprintf(b, "    source: %s\n", yamlString(s.Source))
		if s.Description != "" {
			fmt.Fprintf(b, "    description: %s\n", yamlString(s.Description))
		}
	}
}

func yamlPackages(b *strings.Builder, ps []Package) {
	if len(ps) == 0 {
		b.WriteString("packages: []\n")
		return
	}
	b.WriteString("packages:\n")
	for _, p := range ps {
		fmt.Fprintf(b, "  - id: %s\n", yamlString(p.ID))
		fmt.Fprintf(b, "    name: %s\n", yamlString(p.Name))
		fmt.Fprintf(b, "    importPath: %s\n", yamlString(p.ImportPath))
		if p.Layer != "" {
			fmt.Fprintf(b, "    layer: %s\n", yamlString(p.Layer))
		}
		fmt.Fprintf(b, "    foreign: %t\n", p.Foreign)
		if len(p.Stereotype) > 0 {
			b.WriteString("    stereotypes:\n")
			sort.Strings(p.Stereotype)
			for _, s := range p.Stereotype {
				fmt.Fprintf(b, "      - %s\n", yamlString(s))
			}
		}
		if len(p.Symbols) > 0 {
			b.WriteString("    symbols:\n")
			for _, s := range p.Symbols {
				fmt.Fprintf(b, "      - %s\n", yamlString(s))
			}
		}
		fmt.Fprintf(b, "    archmotifId: %s\n", yamlString(p.ArchmotifID))
	}
}

func yamlSymbols(b *strings.Builder, ss []Symbol) {
	if len(ss) == 0 {
		b.WriteString("symbols: []\n")
		return
	}
	b.WriteString("symbols:\n")
	for _, s := range ss {
		fmt.Fprintf(b, "  - id: %s\n", yamlString(s.ID))
		fmt.Fprintf(b, "    name: %s\n", yamlString(s.Name))
		if s.QName != "" {
			fmt.Fprintf(b, "    qname: %s\n", yamlString(s.QName))
		}
		fmt.Fprintf(b, "    kind: %s\n", yamlString(s.Kind))
		if s.Package != "" {
			fmt.Fprintf(b, "    package: %s\n", yamlString(s.Package))
		}
		if s.Facet != "" {
			fmt.Fprintf(b, "    facet: %s\n", yamlString(s.Facet))
		}
		if len(s.Stereotype) > 0 {
			b.WriteString("    stereotypes:\n")
			for _, st := range s.Stereotype {
				fmt.Fprintf(b, "      - %s\n", yamlString(st))
			}
		}
		fmt.Fprintf(b, "    foreign: %t\n", s.Foreign)
		if s.IsContract {
			b.WriteString("    isContract: true\n")
		}
		if s.Position != nil {
			b.WriteString("    position:\n")
			fmt.Fprintf(b, "      file: %s\n", yamlString(s.Position.File))
			fmt.Fprintf(b, "      line: %d\n", s.Position.Line)
			fmt.Fprintf(b, "      col: %d\n", s.Position.Col)
		}
		fmt.Fprintf(b, "    archmotifId: %s\n", yamlString(s.ArchmotifID))
	}
}

func yamlDependencies(b *strings.Builder, ds []Dependency) {
	if len(ds) == 0 {
		b.WriteString("dependencies: []\n")
		return
	}
	b.WriteString("dependencies:\n")
	for _, d := range ds {
		fmt.Fprintf(b, "  - id: %s\n", yamlString(d.ID))
		fmt.Fprintf(b, "    from: %s\n", yamlString(d.From))
		fmt.Fprintf(b, "    to: %s\n", yamlString(d.To))
		fmt.Fprintf(b, "    relation: %s\n", yamlString(d.Relation))
		fmt.Fprintf(b, "    kind: %s\n", yamlString(d.Kind))
		if d.IsImplementation {
			b.WriteString("    isImplementation: true\n")
		}
		fmt.Fprintf(b, "    fromKind: %s\n", yamlString(d.FromKind))
		fmt.Fprintf(b, "    toKind: %s\n", yamlString(d.ToKind))
	}
}

// yamlString quotes the value when it contains characters that would
// otherwise confuse the YAML parser (colons, leading dashes, hashes,
// etc.). We always double-quote so the encoder stays trivial — the
// alternative (a heuristic for plain scalars) adds bugs without
// shrinking the output meaningfully for our id strings.
func yamlString(s string) string {
	if s == "" {
		return `""`
	}
	// Double-quote and escape the few characters JSON-style escaping
	// covers: backslash, double-quote, newline, tab.
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
